{{- if .Values.ingress.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: {{ .Release.Name }}
spec:
  host: {{ .Values.ingress.host }}
  to:
    kind: Service
    name: {{ .Release.Name }}
  port:
    targetPort: ui
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}
spec:
  host: api-{{ .Values.ingress.host }}
  path: /api
  to:
    kind: Service
    name: {{ .Release.Name }}
  port:
    targetPort: api
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
