apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      name: api
    - port: {{ .Values.service.uiPort }}
      targetPort: ui
      name: ui
  selector:
    app: {{ .Release.Name }}
    component: api
